// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/client.dart';
import 'api/consent.dart';
import 'api/conversations.dart';
import 'api/groups.dart';
import 'api/inbox.dart';
import 'api/messaging.dart';
import 'api/signing.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -134188993;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'xmtp_plugin_native',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<bool> crateApiConversationsAcceptConversation({required String topic});

  Future<bool> crateApiSigningAddAccount(
      {required List<int> newAccountPrivateKey});

  Future<bool> crateApiGroupsAddGroupAdmin(
      {required String topic, required String inboxId});

  Future<bool> crateApiGroupsAddGroupMembers(
      {required String topic, required List<String> inboxIds});

  Future<bool> crateApiGroupsAddGroupSuperAdmin(
      {required String topic, required String inboxId});

  Future<String> crateApiClientAddressFromPrivateKey(
      {required List<int> privateKey});

  Future<bool> crateApiConversationsCanMessage({required String address});

  Future<String> crateApiClientComputeInboxId({required String address});

  Future<String> crateApiConversationsConversationTopicFromAddress(
      {required String address});

  Future<bool> crateApiConversationsDenyConversation({required String topic});

  Future<ConversationInfo> crateApiConversationsFindOrCreateDmWithInboxId(
      {required String inboxId});

  Future<Uint8List> crateApiClientGeneratePrivateKey();

  Future<String> crateApiClientGetClientAddress();

  Future<String> crateApiClientGetClientInboxId();

  Future<String> crateApiConsentGetConversationConsentState(
      {required String topic});

  Future<MemberRoleInfo> crateApiGroupsGetGroupMemberRole(
      {required String topic, required String inboxId});

  Future<String> crateApiConsentGetInboxConsentState({required String inboxId});

  Future<InboxStateInfo> crateApiInboxGetInboxState(
      {required bool refreshFromNetwork});

  Future<String> crateApiInboxGetInstallationId();

  Future<List<MessageInfo>> crateApiMessagingGetMessagesAfterDate(
      {required String peerAddress, required PlatformInt64 fromDateMs});

  Future<List<MessageInfo>> crateApiMessagingGetMessagesAfterDateByTopic(
      {required String topic, required PlatformInt64 fromDateMs});

  Future<String> crateApiClientGetPlatformVersion();

  Future<String> crateApiConversationsInboxIdFromAddress(
      {required String address});

  Future<List<InboxStateInfo>> crateApiGroupsInboxStatesForInboxIds(
      {required List<String> inboxIds, required bool refreshFromNetwork});

  Future<String> crateApiClientInitializeClient(
      {required List<int> privateKey, required List<int> dbEncryptionKey, String environment = 'production'});

  Future<List<ConversationInfo>> crateApiConversationsListConversations(
      {String? consentState});

  Future<List<ConversationInfo>> crateApiConversationsListDms(
      {String? consentState});

  Future<List<String>> crateApiGroupsListGroupAdmins({required String topic});

  Future<List<MemberInfo>> crateApiGroupsListGroupMembers(
      {required String topic});

  Future<List<String>> crateApiGroupsListGroupSuperAdmins(
      {required String topic});

  Future<List<ConversationInfo>> crateApiConversationsListGroups(
      {String? consentState});

  Future<AttachmentInfo> crateApiMessagingLoadRemoteAttachment(
      {required String url,
      required String contentDigest,
      required List<int> secret,
      required List<int> salt,
      required List<int> nonce,
      required String scheme,
      PlatformInt64? contentLength,
      String? filename});

  Future<ConversationInfo> crateApiGroupsNewGroup(
      {required List<String> inboxIds,
      String? name,
      String? imageUrlSquare,
      String? description});

  Future<bool> crateApiSigningRemoveAccount(
      {required List<int> recoveryPrivateKey,
      required String identifierToRemove});

  Future<bool> crateApiGroupsRemoveGroupAdmin(
      {required String topic, required String inboxId});

  Future<bool> crateApiGroupsRemoveGroupMembers(
      {required String topic, required List<String> inboxIds});

  Future<bool> crateApiGroupsRemoveGroupSuperAdmin(
      {required String topic, required String inboxId});

  Future<bool> crateApiSigningRevokeAllOtherInstallations(
      {required List<int> signerPrivateKey});

  Future<bool> crateApiSigningRevokeInstallations(
      {required List<int> signerPrivateKey,
      required List<String> installationIds});

  Future<String> crateApiMessagingSendGroupMessage(
      {required String topic, required List<int> contentBytes});

  Future<String> crateApiMessagingSendMessage(
      {required String address, required List<int> contentBytes});

  Future<String> crateApiMessagingSendMessageByInboxId(
      {required String inboxId, required List<int> contentBytes});

  Future<bool> crateApiInboxSendSyncRequest();

  Future<bool> crateApiConsentSetConversationConsentState(
      {required String topic, required String state});

  Future<bool> crateApiConsentSetInboxConsentState(
      {required String inboxId, required String state});

  Future<List<InboxStateInfo>> crateApiSigningStaticInboxStatesForInboxIds(
      {required List<String> inboxIds});

  Future<bool> crateApiSigningStaticRevokeInstallations(
      {required List<int> signerPrivateKey,
      required String inboxId,
      required List<String> installationIds});

  Stream<MessageInfo> crateApiMessagingSubscribeToAllMessages();

  Future<PlatformInt64> crateApiConversationsSyncAll(
      {List<String>? consentStates});

  Future<bool> crateApiConsentSyncConsentPreferences();

  Future<void> crateApiConversationsSyncConversation({required String topic});

  Future<bool> crateApiGroupsUpdateGroup(
      {required String topic,
      String? name,
      String? description,
      String? imageUrl});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<bool> crateApiConversationsAcceptConversation(
      {required String topic}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(topic, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiConversationsAcceptConversationConstMeta,
      argValues: [topic],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiConversationsAcceptConversationConstMeta =>
      const TaskConstMeta(
        debugName: "accept_conversation",
        argNames: ["topic"],
      );

  @override
  Future<bool> crateApiSigningAddAccount(
      {required List<int> newAccountPrivateKey}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(newAccountPrivateKey, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSigningAddAccountConstMeta,
      argValues: [newAccountPrivateKey],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSigningAddAccountConstMeta => const TaskConstMeta(
        debugName: "add_account",
        argNames: ["newAccountPrivateKey"],
      );

  @override
  Future<bool> crateApiGroupsAddGroupAdmin(
      {required String topic, required String inboxId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(topic, serializer);
        sse_encode_String(inboxId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiGroupsAddGroupAdminConstMeta,
      argValues: [topic, inboxId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGroupsAddGroupAdminConstMeta =>
      const TaskConstMeta(
        debugName: "add_group_admin",
        argNames: ["topic", "inboxId"],
      );

  @override
  Future<bool> crateApiGroupsAddGroupMembers(
      {required String topic, required List<String> inboxIds}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(topic, serializer);
        sse_encode_list_String(inboxIds, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiGroupsAddGroupMembersConstMeta,
      argValues: [topic, inboxIds],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGroupsAddGroupMembersConstMeta =>
      const TaskConstMeta(
        debugName: "add_group_members",
        argNames: ["topic", "inboxIds"],
      );

  @override
  Future<bool> crateApiGroupsAddGroupSuperAdmin(
      {required String topic, required String inboxId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(topic, serializer);
        sse_encode_String(inboxId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiGroupsAddGroupSuperAdminConstMeta,
      argValues: [topic, inboxId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGroupsAddGroupSuperAdminConstMeta =>
      const TaskConstMeta(
        debugName: "add_group_super_admin",
        argNames: ["topic", "inboxId"],
      );

  @override
  Future<String> crateApiClientAddressFromPrivateKey(
      {required List<int> privateKey}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(privateKey, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiClientAddressFromPrivateKeyConstMeta,
      argValues: [privateKey],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiClientAddressFromPrivateKeyConstMeta =>
      const TaskConstMeta(
        debugName: "address_from_private_key",
        argNames: ["privateKey"],
      );

  @override
  Future<bool> crateApiConversationsCanMessage({required String address}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(address, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiConversationsCanMessageConstMeta,
      argValues: [address],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiConversationsCanMessageConstMeta =>
      const TaskConstMeta(
        debugName: "can_message",
        argNames: ["address"],
      );

  @override
  Future<String> crateApiClientComputeInboxId({required String address}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(address, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiClientComputeInboxIdConstMeta,
      argValues: [address],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiClientComputeInboxIdConstMeta =>
      const TaskConstMeta(
        debugName: "compute_inbox_id",
        argNames: ["address"],
      );

  @override
  Future<String> crateApiConversationsConversationTopicFromAddress(
      {required String address}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(address, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiConversationsConversationTopicFromAddressConstMeta,
      argValues: [address],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiConversationsConversationTopicFromAddressConstMeta =>
          const TaskConstMeta(
            debugName: "conversation_topic_from_address",
            argNames: ["address"],
          );

  @override
  Future<bool> crateApiConversationsDenyConversation({required String topic}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(topic, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiConversationsDenyConversationConstMeta,
      argValues: [topic],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiConversationsDenyConversationConstMeta =>
      const TaskConstMeta(
        debugName: "deny_conversation",
        argNames: ["topic"],
      );

  @override
  Future<ConversationInfo> crateApiConversationsFindOrCreateDmWithInboxId(
      {required String inboxId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(inboxId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_conversation_info,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiConversationsFindOrCreateDmWithInboxIdConstMeta,
      argValues: [inboxId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiConversationsFindOrCreateDmWithInboxIdConstMeta =>
      const TaskConstMeta(
        debugName: "find_or_create_dm_with_inbox_id",
        argNames: ["inboxId"],
      );

  @override
  Future<Uint8List> crateApiClientGeneratePrivateKey() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiClientGeneratePrivateKeyConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiClientGeneratePrivateKeyConstMeta =>
      const TaskConstMeta(
        debugName: "generate_private_key",
        argNames: [],
      );

  @override
  Future<String> crateApiClientGetClientAddress() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiClientGetClientAddressConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiClientGetClientAddressConstMeta =>
      const TaskConstMeta(
        debugName: "get_client_address",
        argNames: [],
      );

  @override
  Future<String> crateApiClientGetClientInboxId() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiClientGetClientInboxIdConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiClientGetClientInboxIdConstMeta =>
      const TaskConstMeta(
        debugName: "get_client_inbox_id",
        argNames: [],
      );

  @override
  Future<String> crateApiConsentGetConversationConsentState(
      {required String topic}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(topic, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiConsentGetConversationConsentStateConstMeta,
      argValues: [topic],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiConsentGetConversationConsentStateConstMeta =>
      const TaskConstMeta(
        debugName: "get_conversation_consent_state",
        argNames: ["topic"],
      );

  @override
  Future<MemberRoleInfo> crateApiGroupsGetGroupMemberRole(
      {required String topic, required String inboxId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(topic, serializer);
        sse_encode_String(inboxId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_member_role_info,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiGroupsGetGroupMemberRoleConstMeta,
      argValues: [topic, inboxId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGroupsGetGroupMemberRoleConstMeta =>
      const TaskConstMeta(
        debugName: "get_group_member_role",
        argNames: ["topic", "inboxId"],
      );

  @override
  Future<String> crateApiConsentGetInboxConsentState(
      {required String inboxId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(inboxId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiConsentGetInboxConsentStateConstMeta,
      argValues: [inboxId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiConsentGetInboxConsentStateConstMeta =>
      const TaskConstMeta(
        debugName: "get_inbox_consent_state",
        argNames: ["inboxId"],
      );

  @override
  Future<InboxStateInfo> crateApiInboxGetInboxState(
      {required bool refreshFromNetwork}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_bool(refreshFromNetwork, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 18, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_inbox_state_info,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiInboxGetInboxStateConstMeta,
      argValues: [refreshFromNetwork],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInboxGetInboxStateConstMeta => const TaskConstMeta(
        debugName: "get_inbox_state",
        argNames: ["refreshFromNetwork"],
      );

  @override
  Future<String> crateApiInboxGetInstallationId() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 19, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiInboxGetInstallationIdConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInboxGetInstallationIdConstMeta =>
      const TaskConstMeta(
        debugName: "get_installation_id",
        argNames: [],
      );

  @override
  Future<List<MessageInfo>> crateApiMessagingGetMessagesAfterDate(
      {required String peerAddress, required PlatformInt64 fromDateMs}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(peerAddress, serializer);
        sse_encode_i_64(fromDateMs, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 20, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_message_info,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiMessagingGetMessagesAfterDateConstMeta,
      argValues: [peerAddress, fromDateMs],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMessagingGetMessagesAfterDateConstMeta =>
      const TaskConstMeta(
        debugName: "get_messages_after_date",
        argNames: ["peerAddress", "fromDateMs"],
      );

  @override
  Future<List<MessageInfo>> crateApiMessagingGetMessagesAfterDateByTopic(
      {required String topic, required PlatformInt64 fromDateMs}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(topic, serializer);
        sse_encode_i_64(fromDateMs, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 21, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_message_info,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiMessagingGetMessagesAfterDateByTopicConstMeta,
      argValues: [topic, fromDateMs],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMessagingGetMessagesAfterDateByTopicConstMeta =>
      const TaskConstMeta(
        debugName: "get_messages_after_date_by_topic",
        argNames: ["topic", "fromDateMs"],
      );

  @override
  Future<String> crateApiClientGetPlatformVersion() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 22, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiClientGetPlatformVersionConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiClientGetPlatformVersionConstMeta =>
      const TaskConstMeta(
        debugName: "get_platform_version",
        argNames: [],
      );

  @override
  Future<String> crateApiConversationsInboxIdFromAddress(
      {required String address}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(address, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 23, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiConversationsInboxIdFromAddressConstMeta,
      argValues: [address],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiConversationsInboxIdFromAddressConstMeta =>
      const TaskConstMeta(
        debugName: "inbox_id_from_address",
        argNames: ["address"],
      );

  @override
  Future<List<InboxStateInfo>> crateApiGroupsInboxStatesForInboxIds(
      {required List<String> inboxIds, required bool refreshFromNetwork}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_String(inboxIds, serializer);
        sse_encode_bool(refreshFromNetwork, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 24, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_inbox_state_info,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiGroupsInboxStatesForInboxIdsConstMeta,
      argValues: [inboxIds, refreshFromNetwork],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGroupsInboxStatesForInboxIdsConstMeta =>
      const TaskConstMeta(
        debugName: "inbox_states_for_inbox_ids",
        argNames: ["inboxIds", "refreshFromNetwork"],
      );

  @override
  Future<String> crateApiClientInitializeClient(
      {required List<int> privateKey, required List<int> dbEncryptionKey, String environment = 'production'}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(privateKey, serializer);
        sse_encode_list_prim_u_8_loose(dbEncryptionKey, serializer);
        sse_encode_String(environment, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 25, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiClientInitializeClientConstMeta,
      argValues: [privateKey, dbEncryptionKey, environment],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiClientInitializeClientConstMeta =>
      const TaskConstMeta(
        debugName: "initialize_client",
        argNames: ["privateKey", "dbEncryptionKey", "environment"],
      );

  @override
  Future<List<ConversationInfo>> crateApiConversationsListConversations(
      {String? consentState}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_opt_String(consentState, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 26, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_conversation_info,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiConversationsListConversationsConstMeta,
      argValues: [consentState],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiConversationsListConversationsConstMeta =>
      const TaskConstMeta(
        debugName: "list_conversations",
        argNames: ["consentState"],
      );

  @override
  Future<List<ConversationInfo>> crateApiConversationsListDms(
      {String? consentState}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_opt_String(consentState, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 27, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_conversation_info,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiConversationsListDmsConstMeta,
      argValues: [consentState],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiConversationsListDmsConstMeta =>
      const TaskConstMeta(
        debugName: "list_dms",
        argNames: ["consentState"],
      );

  @override
  Future<List<String>> crateApiGroupsListGroupAdmins({required String topic}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(topic, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 28, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiGroupsListGroupAdminsConstMeta,
      argValues: [topic],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGroupsListGroupAdminsConstMeta =>
      const TaskConstMeta(
        debugName: "list_group_admins",
        argNames: ["topic"],
      );

  @override
  Future<List<MemberInfo>> crateApiGroupsListGroupMembers(
      {required String topic}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(topic, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 29, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_member_info,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiGroupsListGroupMembersConstMeta,
      argValues: [topic],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGroupsListGroupMembersConstMeta =>
      const TaskConstMeta(
        debugName: "list_group_members",
        argNames: ["topic"],
      );

  @override
  Future<List<String>> crateApiGroupsListGroupSuperAdmins(
      {required String topic}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(topic, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 30, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiGroupsListGroupSuperAdminsConstMeta,
      argValues: [topic],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGroupsListGroupSuperAdminsConstMeta =>
      const TaskConstMeta(
        debugName: "list_group_super_admins",
        argNames: ["topic"],
      );

  @override
  Future<List<ConversationInfo>> crateApiConversationsListGroups(
      {String? consentState}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_opt_String(consentState, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 31, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_conversation_info,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiConversationsListGroupsConstMeta,
      argValues: [consentState],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiConversationsListGroupsConstMeta =>
      const TaskConstMeta(
        debugName: "list_groups",
        argNames: ["consentState"],
      );

  @override
  Future<AttachmentInfo> crateApiMessagingLoadRemoteAttachment(
      {required String url,
      required String contentDigest,
      required List<int> secret,
      required List<int> salt,
      required List<int> nonce,
      required String scheme,
      PlatformInt64? contentLength,
      String? filename}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(url, serializer);
        sse_encode_String(contentDigest, serializer);
        sse_encode_list_prim_u_8_loose(secret, serializer);
        sse_encode_list_prim_u_8_loose(salt, serializer);
        sse_encode_list_prim_u_8_loose(nonce, serializer);
        sse_encode_String(scheme, serializer);
        sse_encode_opt_box_autoadd_i_64(contentLength, serializer);
        sse_encode_opt_String(filename, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 32, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_attachment_info,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiMessagingLoadRemoteAttachmentConstMeta,
      argValues: [
        url,
        contentDigest,
        secret,
        salt,
        nonce,
        scheme,
        contentLength,
        filename
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMessagingLoadRemoteAttachmentConstMeta =>
      const TaskConstMeta(
        debugName: "load_remote_attachment",
        argNames: [
          "url",
          "contentDigest",
          "secret",
          "salt",
          "nonce",
          "scheme",
          "contentLength",
          "filename"
        ],
      );

  @override
  Future<ConversationInfo> crateApiGroupsNewGroup(
      {required List<String> inboxIds,
      String? name,
      String? imageUrlSquare,
      String? description}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_String(inboxIds, serializer);
        sse_encode_opt_String(name, serializer);
        sse_encode_opt_String(imageUrlSquare, serializer);
        sse_encode_opt_String(description, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 33, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_conversation_info,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiGroupsNewGroupConstMeta,
      argValues: [inboxIds, name, imageUrlSquare, description],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGroupsNewGroupConstMeta => const TaskConstMeta(
        debugName: "new_group",
        argNames: ["inboxIds", "name", "imageUrlSquare", "description"],
      );

  @override
  Future<bool> crateApiSigningRemoveAccount(
      {required List<int> recoveryPrivateKey,
      required String identifierToRemove}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(recoveryPrivateKey, serializer);
        sse_encode_String(identifierToRemove, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 34, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSigningRemoveAccountConstMeta,
      argValues: [recoveryPrivateKey, identifierToRemove],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSigningRemoveAccountConstMeta =>
      const TaskConstMeta(
        debugName: "remove_account",
        argNames: ["recoveryPrivateKey", "identifierToRemove"],
      );

  @override
  Future<bool> crateApiGroupsRemoveGroupAdmin(
      {required String topic, required String inboxId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(topic, serializer);
        sse_encode_String(inboxId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 35, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiGroupsRemoveGroupAdminConstMeta,
      argValues: [topic, inboxId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGroupsRemoveGroupAdminConstMeta =>
      const TaskConstMeta(
        debugName: "remove_group_admin",
        argNames: ["topic", "inboxId"],
      );

  @override
  Future<bool> crateApiGroupsRemoveGroupMembers(
      {required String topic, required List<String> inboxIds}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(topic, serializer);
        sse_encode_list_String(inboxIds, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 36, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiGroupsRemoveGroupMembersConstMeta,
      argValues: [topic, inboxIds],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGroupsRemoveGroupMembersConstMeta =>
      const TaskConstMeta(
        debugName: "remove_group_members",
        argNames: ["topic", "inboxIds"],
      );

  @override
  Future<bool> crateApiGroupsRemoveGroupSuperAdmin(
      {required String topic, required String inboxId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(topic, serializer);
        sse_encode_String(inboxId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 37, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiGroupsRemoveGroupSuperAdminConstMeta,
      argValues: [topic, inboxId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGroupsRemoveGroupSuperAdminConstMeta =>
      const TaskConstMeta(
        debugName: "remove_group_super_admin",
        argNames: ["topic", "inboxId"],
      );

  @override
  Future<bool> crateApiSigningRevokeAllOtherInstallations(
      {required List<int> signerPrivateKey}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(signerPrivateKey, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 38, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSigningRevokeAllOtherInstallationsConstMeta,
      argValues: [signerPrivateKey],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSigningRevokeAllOtherInstallationsConstMeta =>
      const TaskConstMeta(
        debugName: "revoke_all_other_installations",
        argNames: ["signerPrivateKey"],
      );

  @override
  Future<bool> crateApiSigningRevokeInstallations(
      {required List<int> signerPrivateKey,
      required List<String> installationIds}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(signerPrivateKey, serializer);
        sse_encode_list_String(installationIds, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 39, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSigningRevokeInstallationsConstMeta,
      argValues: [signerPrivateKey, installationIds],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSigningRevokeInstallationsConstMeta =>
      const TaskConstMeta(
        debugName: "revoke_installations",
        argNames: ["signerPrivateKey", "installationIds"],
      );

  @override
  Future<String> crateApiMessagingSendGroupMessage(
      {required String topic, required List<int> contentBytes}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(topic, serializer);
        sse_encode_list_prim_u_8_loose(contentBytes, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 40, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiMessagingSendGroupMessageConstMeta,
      argValues: [topic, contentBytes],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMessagingSendGroupMessageConstMeta =>
      const TaskConstMeta(
        debugName: "send_group_message",
        argNames: ["topic", "contentBytes"],
      );

  @override
  Future<String> crateApiMessagingSendMessage(
      {required String address, required List<int> contentBytes}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(address, serializer);
        sse_encode_list_prim_u_8_loose(contentBytes, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 41, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiMessagingSendMessageConstMeta,
      argValues: [address, contentBytes],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMessagingSendMessageConstMeta =>
      const TaskConstMeta(
        debugName: "send_message",
        argNames: ["address", "contentBytes"],
      );

  @override
  Future<String> crateApiMessagingSendMessageByInboxId(
      {required String inboxId, required List<int> contentBytes}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(inboxId, serializer);
        sse_encode_list_prim_u_8_loose(contentBytes, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 42, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiMessagingSendMessageByInboxIdConstMeta,
      argValues: [inboxId, contentBytes],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMessagingSendMessageByInboxIdConstMeta =>
      const TaskConstMeta(
        debugName: "send_message_by_inbox_id",
        argNames: ["inboxId", "contentBytes"],
      );

  @override
  Future<bool> crateApiInboxSendSyncRequest() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 43, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiInboxSendSyncRequestConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInboxSendSyncRequestConstMeta =>
      const TaskConstMeta(
        debugName: "send_sync_request",
        argNames: [],
      );

  @override
  Future<bool> crateApiConsentSetConversationConsentState(
      {required String topic, required String state}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(topic, serializer);
        sse_encode_String(state, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 44, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiConsentSetConversationConsentStateConstMeta,
      argValues: [topic, state],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiConsentSetConversationConsentStateConstMeta =>
      const TaskConstMeta(
        debugName: "set_conversation_consent_state",
        argNames: ["topic", "state"],
      );

  @override
  Future<bool> crateApiConsentSetInboxConsentState(
      {required String inboxId, required String state}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(inboxId, serializer);
        sse_encode_String(state, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 45, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiConsentSetInboxConsentStateConstMeta,
      argValues: [inboxId, state],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiConsentSetInboxConsentStateConstMeta =>
      const TaskConstMeta(
        debugName: "set_inbox_consent_state",
        argNames: ["inboxId", "state"],
      );

  @override
  Future<List<InboxStateInfo>> crateApiSigningStaticInboxStatesForInboxIds(
      {required List<String> inboxIds}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_String(inboxIds, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 46, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_inbox_state_info,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSigningStaticInboxStatesForInboxIdsConstMeta,
      argValues: [inboxIds],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSigningStaticInboxStatesForInboxIdsConstMeta =>
      const TaskConstMeta(
        debugName: "static_inbox_states_for_inbox_ids",
        argNames: ["inboxIds"],
      );

  @override
  Future<bool> crateApiSigningStaticRevokeInstallations(
      {required List<int> signerPrivateKey,
      required String inboxId,
      required List<String> installationIds}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(signerPrivateKey, serializer);
        sse_encode_String(inboxId, serializer);
        sse_encode_list_String(installationIds, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 47, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSigningStaticRevokeInstallationsConstMeta,
      argValues: [signerPrivateKey, inboxId, installationIds],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSigningStaticRevokeInstallationsConstMeta =>
      const TaskConstMeta(
        debugName: "static_revoke_installations",
        argNames: ["signerPrivateKey", "inboxId", "installationIds"],
      );

  @override
  Stream<MessageInfo> crateApiMessagingSubscribeToAllMessages() {
    final sink = RustStreamSink<MessageInfo>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_StreamSink_message_info_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 48, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiMessagingSubscribeToAllMessagesConstMeta,
      argValues: [sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiMessagingSubscribeToAllMessagesConstMeta =>
      const TaskConstMeta(
        debugName: "subscribe_to_all_messages",
        argNames: ["sink"],
      );

  @override
  Future<PlatformInt64> crateApiConversationsSyncAll(
      {List<String>? consentStates}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_opt_list_String(consentStates, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 49, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_i_64,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiConversationsSyncAllConstMeta,
      argValues: [consentStates],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiConversationsSyncAllConstMeta =>
      const TaskConstMeta(
        debugName: "sync_all",
        argNames: ["consentStates"],
      );

  @override
  Future<bool> crateApiConsentSyncConsentPreferences() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 50, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiConsentSyncConsentPreferencesConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiConsentSyncConsentPreferencesConstMeta =>
      const TaskConstMeta(
        debugName: "sync_consent_preferences",
        argNames: [],
      );

  @override
  Future<void> crateApiConversationsSyncConversation({required String topic}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(topic, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 51, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiConversationsSyncConversationConstMeta,
      argValues: [topic],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiConversationsSyncConversationConstMeta =>
      const TaskConstMeta(
        debugName: "sync_conversation",
        argNames: ["topic"],
      );

  @override
  Future<bool> crateApiGroupsUpdateGroup(
      {required String topic,
      String? name,
      String? description,
      String? imageUrl}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(topic, serializer);
        sse_encode_opt_String(name, serializer);
        sse_encode_opt_String(description, serializer);
        sse_encode_opt_String(imageUrl, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 52, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiGroupsUpdateGroupConstMeta,
      argValues: [topic, name, description, imageUrl],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGroupsUpdateGroupConstMeta => const TaskConstMeta(
        debugName: "update_group",
        argNames: ["topic", "name", "description", "imageUrl"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<MessageInfo> dco_decode_StreamSink_message_info_Sse(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AttachmentInfo dco_decode_attachment_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return AttachmentInfo(
      filename: dco_decode_String(arr[0]),
      mimeType: dco_decode_String(arr[1]),
      data: dco_decode_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  ConversationInfo dco_decode_conversation_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return ConversationInfo(
      id: dco_decode_String(arr[0]),
      topic: dco_decode_String(arr[1]),
      createdAtMs: dco_decode_i_64(arr[2]),
      conversationType: dco_decode_String(arr[3]),
      peerInboxId: dco_decode_opt_String(arr[4]),
      name: dco_decode_opt_String(arr[5]),
      imageUrlSquare: dco_decode_opt_String(arr[6]),
      description: dco_decode_opt_String(arr[7]),
      members: dco_decode_list_member_info(arr[8]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  IdentityInfo dco_decode_identity_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return IdentityInfo(
      identifier: dco_decode_String(arr[0]),
      kind: dco_decode_String(arr[1]),
    );
  }

  @protected
  InboxStateInfo dco_decode_inbox_state_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return InboxStateInfo(
      inboxId: dco_decode_String(arr[0]),
      identities: dco_decode_list_identity_info(arr[1]),
      installations: dco_decode_list_installation_info(arr[2]),
      recoveryIdentity: dco_decode_identity_info(arr[3]),
    );
  }

  @protected
  InstallationInfo dco_decode_installation_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return InstallationInfo(
      id: dco_decode_String(arr[0]),
      createdAt: dco_decode_opt_box_autoadd_i_64(arr[1]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<ConversationInfo> dco_decode_list_conversation_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_conversation_info).toList();
  }

  @protected
  List<IdentityInfo> dco_decode_list_identity_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_identity_info).toList();
  }

  @protected
  List<InboxStateInfo> dco_decode_list_inbox_state_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_inbox_state_info).toList();
  }

  @protected
  List<InstallationInfo> dco_decode_list_installation_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_installation_info).toList();
  }

  @protected
  List<MemberInfo> dco_decode_list_member_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_member_info).toList();
  }

  @protected
  List<MessageInfo> dco_decode_list_message_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_message_info).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MemberInfo dco_decode_member_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return MemberInfo(
      inboxId: dco_decode_String(arr[0]),
      address: dco_decode_String(arr[1]),
    );
  }

  @protected
  MemberRoleInfo dco_decode_member_role_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return MemberRoleInfo(
      isAdmin: dco_decode_bool(arr[0]),
      isSuperAdmin: dco_decode_bool(arr[1]),
    );
  }

  @protected
  MessageInfo dco_decode_message_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return MessageInfo(
      id: dco_decode_String(arr[0]),
      sentAtMs: dco_decode_i_64(arr[1]),
      senderInboxId: dco_decode_String(arr[2]),
      conversationTopic: dco_decode_String(arr[3]),
      encodedContentBytes: dco_decode_list_prim_u_8_strict(arr[4]),
      members: dco_decode_list_member_info(arr[5]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_String(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<MessageInfo> sse_decode_StreamSink_message_info_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AttachmentInfo sse_decode_attachment_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_filename = sse_decode_String(deserializer);
    var var_mimeType = sse_decode_String(deserializer);
    var var_data = sse_decode_list_prim_u_8_strict(deserializer);
    return AttachmentInfo(
        filename: var_filename, mimeType: var_mimeType, data: var_data);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  ConversationInfo sse_decode_conversation_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_topic = sse_decode_String(deserializer);
    var var_createdAtMs = sse_decode_i_64(deserializer);
    var var_conversationType = sse_decode_String(deserializer);
    var var_peerInboxId = sse_decode_opt_String(deserializer);
    var var_name = sse_decode_opt_String(deserializer);
    var var_imageUrlSquare = sse_decode_opt_String(deserializer);
    var var_description = sse_decode_opt_String(deserializer);
    var var_members = sse_decode_list_member_info(deserializer);
    return ConversationInfo(
        id: var_id,
        topic: var_topic,
        createdAtMs: var_createdAtMs,
        conversationType: var_conversationType,
        peerInboxId: var_peerInboxId,
        name: var_name,
        imageUrlSquare: var_imageUrlSquare,
        description: var_description,
        members: var_members);
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  IdentityInfo sse_decode_identity_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_identifier = sse_decode_String(deserializer);
    var var_kind = sse_decode_String(deserializer);
    return IdentityInfo(identifier: var_identifier, kind: var_kind);
  }

  @protected
  InboxStateInfo sse_decode_inbox_state_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_inboxId = sse_decode_String(deserializer);
    var var_identities = sse_decode_list_identity_info(deserializer);
    var var_installations = sse_decode_list_installation_info(deserializer);
    var var_recoveryIdentity = sse_decode_identity_info(deserializer);
    return InboxStateInfo(
        inboxId: var_inboxId,
        identities: var_identities,
        installations: var_installations,
        recoveryIdentity: var_recoveryIdentity);
  }

  @protected
  InstallationInfo sse_decode_installation_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_opt_box_autoadd_i_64(deserializer);
    return InstallationInfo(id: var_id, createdAt: var_createdAt);
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ConversationInfo> sse_decode_list_conversation_info(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ConversationInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_conversation_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<IdentityInfo> sse_decode_list_identity_info(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <IdentityInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_identity_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<InboxStateInfo> sse_decode_list_inbox_state_info(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <InboxStateInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_inbox_state_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<InstallationInfo> sse_decode_list_installation_info(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <InstallationInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_installation_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<MemberInfo> sse_decode_list_member_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MemberInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_member_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<MessageInfo> sse_decode_list_message_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MessageInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_message_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MemberInfo sse_decode_member_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_inboxId = sse_decode_String(deserializer);
    var var_address = sse_decode_String(deserializer);
    return MemberInfo(inboxId: var_inboxId, address: var_address);
  }

  @protected
  MemberRoleInfo sse_decode_member_role_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_isAdmin = sse_decode_bool(deserializer);
    var var_isSuperAdmin = sse_decode_bool(deserializer);
    return MemberRoleInfo(isAdmin: var_isAdmin, isSuperAdmin: var_isSuperAdmin);
  }

  @protected
  MessageInfo sse_decode_message_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_sentAtMs = sse_decode_i_64(deserializer);
    var var_senderInboxId = sse_decode_String(deserializer);
    var var_conversationTopic = sse_decode_String(deserializer);
    var var_encodedContentBytes = sse_decode_list_prim_u_8_strict(deserializer);
    var var_members = sse_decode_list_member_info(deserializer);
    return MessageInfo(
        id: var_id,
        sentAtMs: var_sentAtMs,
        senderInboxId: var_senderInboxId,
        conversationTopic: var_conversationTopic,
        encodedContentBytes: var_encodedContentBytes,
        members: var_members);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_message_info_Sse(
      RustStreamSink<MessageInfo> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_message_info,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_attachment_info(
      AttachmentInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.filename, serializer);
    sse_encode_String(self.mimeType, serializer);
    sse_encode_list_prim_u_8_strict(self.data, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
      PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_conversation_info(
      ConversationInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.topic, serializer);
    sse_encode_i_64(self.createdAtMs, serializer);
    sse_encode_String(self.conversationType, serializer);
    sse_encode_opt_String(self.peerInboxId, serializer);
    sse_encode_opt_String(self.name, serializer);
    sse_encode_opt_String(self.imageUrlSquare, serializer);
    sse_encode_opt_String(self.description, serializer);
    sse_encode_list_member_info(self.members, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_identity_info(IdentityInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.identifier, serializer);
    sse_encode_String(self.kind, serializer);
  }

  @protected
  void sse_encode_inbox_state_info(
      InboxStateInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.inboxId, serializer);
    sse_encode_list_identity_info(self.identities, serializer);
    sse_encode_list_installation_info(self.installations, serializer);
    sse_encode_identity_info(self.recoveryIdentity, serializer);
  }

  @protected
  void sse_encode_installation_info(
      InstallationInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_opt_box_autoadd_i_64(self.createdAt, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_conversation_info(
      List<ConversationInfo> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_conversation_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_identity_info(
      List<IdentityInfo> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_identity_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_inbox_state_info(
      List<InboxStateInfo> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_inbox_state_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_installation_info(
      List<InstallationInfo> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_installation_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_member_info(
      List<MemberInfo> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_member_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_message_info(
      List<MessageInfo> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_message_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
      List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer
        .putUint8List(self is Uint8List ? self : Uint8List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_member_info(MemberInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.inboxId, serializer);
    sse_encode_String(self.address, serializer);
  }

  @protected
  void sse_encode_member_role_info(
      MemberRoleInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.isAdmin, serializer);
    sse_encode_bool(self.isSuperAdmin, serializer);
  }

  @protected
  void sse_encode_message_info(MessageInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_i_64(self.sentAtMs, serializer);
    sse_encode_String(self.senderInboxId, serializer);
    sse_encode_String(self.conversationTopic, serializer);
    sse_encode_list_prim_u_8_strict(self.encodedContentBytes, serializer);
    sse_encode_list_member_info(self.members, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
      PlatformInt64? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_String(
      List<String>? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_String(self, serializer);
    }
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
