// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/client.dart';
import 'api/consent.dart';
import 'api/conversations.dart';
import 'api/groups.dart';
import 'api/inbox.dart';
import 'api/messaging.dart';
import 'api/signing.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<MessageInfo> dco_decode_StreamSink_message_info_Sse(
      dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AttachmentInfo dco_decode_attachment_info(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  ConversationInfo dco_decode_conversation_info(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  IdentityInfo dco_decode_identity_info(dynamic raw);

  @protected
  InboxStateInfo dco_decode_inbox_state_info(dynamic raw);

  @protected
  InstallationInfo dco_decode_installation_info(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ConversationInfo> dco_decode_list_conversation_info(dynamic raw);

  @protected
  List<IdentityInfo> dco_decode_list_identity_info(dynamic raw);

  @protected
  List<InboxStateInfo> dco_decode_list_inbox_state_info(dynamic raw);

  @protected
  List<InstallationInfo> dco_decode_list_installation_info(dynamic raw);

  @protected
  List<MemberInfo> dco_decode_list_member_info(dynamic raw);

  @protected
  List<MessageInfo> dco_decode_list_message_info(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  MemberInfo dco_decode_member_info(dynamic raw);

  @protected
  MemberRoleInfo dco_decode_member_role_info(dynamic raw);

  @protected
  MessageInfo dco_decode_message_info(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<MessageInfo> sse_decode_StreamSink_message_info_Sse(
      SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AttachmentInfo sse_decode_attachment_info(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  ConversationInfo sse_decode_conversation_info(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  IdentityInfo sse_decode_identity_info(SseDeserializer deserializer);

  @protected
  InboxStateInfo sse_decode_inbox_state_info(SseDeserializer deserializer);

  @protected
  InstallationInfo sse_decode_installation_info(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ConversationInfo> sse_decode_list_conversation_info(
      SseDeserializer deserializer);

  @protected
  List<IdentityInfo> sse_decode_list_identity_info(
      SseDeserializer deserializer);

  @protected
  List<InboxStateInfo> sse_decode_list_inbox_state_info(
      SseDeserializer deserializer);

  @protected
  List<InstallationInfo> sse_decode_list_installation_info(
      SseDeserializer deserializer);

  @protected
  List<MemberInfo> sse_decode_list_member_info(SseDeserializer deserializer);

  @protected
  List<MessageInfo> sse_decode_list_message_info(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  MemberInfo sse_decode_member_info(SseDeserializer deserializer);

  @protected
  MemberRoleInfo sse_decode_member_role_info(SseDeserializer deserializer);

  @protected
  MessageInfo sse_decode_message_info(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_message_info_Sse(
      RustStreamSink<MessageInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_attachment_info(
      AttachmentInfo self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
      PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_conversation_info(
      ConversationInfo self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_identity_info(IdentityInfo self, SseSerializer serializer);

  @protected
  void sse_encode_inbox_state_info(
      InboxStateInfo self, SseSerializer serializer);

  @protected
  void sse_encode_installation_info(
      InstallationInfo self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_conversation_info(
      List<ConversationInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_identity_info(
      List<IdentityInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_inbox_state_info(
      List<InboxStateInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_installation_info(
      List<InstallationInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_member_info(
      List<MemberInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_message_info(
      List<MessageInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_member_info(MemberInfo self, SseSerializer serializer);

  @protected
  void sse_encode_member_role_info(
      MemberRoleInfo self, SseSerializer serializer);

  @protected
  void sse_encode_message_info(MessageInfo self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
      PlatformInt64? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;
}
