// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_options`, `check_key`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`

/// Write an encrypted archive of the active client's MLS store to `path`.
/// `key` must be >= 32 bytes (first 32 used). Mirrors
/// `bindings_ffi/src/mls.rs::create_archive`.
///
/// NOTE: an EMPTY `elements` vec archives NOTHING (metadata frame only) —
/// upstream `xmtp_archive::BatchExportStream` builds one input stream per
/// selected element, so empty ⇒ zero streams. The "empty = both" default is
/// applied one layer up in the Dart facade `exportArchive`
/// (`lib/xmtp_plugin.dart`); never call this with an empty vec expecting both.
Future<void> createArchive(
        {required String path,
        required List<int> key,
        required List<BackupElement> elements,
        PlatformInt64? startNs,
        PlatformInt64? endNs,
        required bool excludeDisappearingMessages}) =>
    RustLib.instance.api.crateApiArchiveCreateArchive(
        path: path,
        key: key,
        elements: elements,
        startNs: startNs,
        endNs: endNs,
        excludeDisappearingMessages: excludeDisappearingMessages);

/// Decrypt + import an archive at `path` into the active client's MLS store
/// (additive). A wrong key (bad password / different inbox) fails to decrypt in
/// `from_file` before any write. Mirrors `import_archive`.
Future<void> importArchive({required String path, required List<int> key}) =>
    RustLib.instance.api.crateApiArchiveImportArchive(path: path, key: key);

/// Read the archive header without importing. Also verifies the key — a wrong
/// password makes `from_file` fail to decrypt. Mirrors `archive_metadata`.
Future<ArchiveMetadata> archiveMetadata(
        {required String path, required List<int> key}) =>
    RustLib.instance.api.crateApiArchiveArchiveMetadata(path: path, key: key);

/// Archive header (scope/counts/time range), read without importing.
class ArchiveMetadata {
  final int backupVersion;
  final List<BackupElement> elements;
  final PlatformInt64 exportedAtNs;
  final PlatformInt64? startNs;
  final PlatformInt64? endNs;

  const ArchiveMetadata({
    required this.backupVersion,
    required this.elements,
    required this.exportedAtNs,
    this.startNs,
    this.endNs,
  });

  @override
  int get hashCode =>
      backupVersion.hashCode ^
      elements.hashCode ^
      exportedAtNs.hashCode ^
      startNs.hashCode ^
      endNs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArchiveMetadata &&
          runtimeType == other.runtimeType &&
          backupVersion == other.backupVersion &&
          elements == other.elements &&
          exportedAtNs == other.exportedAtNs &&
          startNs == other.startNs &&
          endNs == other.endNs;
}

/// Which application data an archive carries. An empty selection at the call
/// site means both (the upstream default). Mirrors
/// `xmtp_proto::xmtp::device_sync::BackupElementSelection`.
enum BackupElement {
  messages,
  consent,
  ;
}
