// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `eth_address_from_key`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ClientState`

/// Returns the platform version string.
Future<String> getPlatformVersion() =>
    RustLib.instance.api.crateApiClientGetPlatformVersion();

/// Generate a random secp256k1 private key. Returns 32 raw bytes.
Future<Uint8List> generatePrivateKey() =>
    RustLib.instance.api.crateApiClientGeneratePrivateKey();

/// Derive the Ethereum address from a 32-byte secp256k1 private key.
/// Returns a checksumless, lowercased, 0x-prefixed hex string (42 chars).
Future<String> addressFromPrivateKey({required List<int> privateKey}) =>
    RustLib.instance.api
        .crateApiClientAddressFromPrivateKey(privateKey: privateKey);

/// Compute the XMTP inbox ID for a given Ethereum address.
/// The inbox ID is deterministic: sha256(lowercased_address + nonce).
Future<String> computeInboxId({required String address}) =>
    RustLib.instance.api.crateApiClientComputeInboxId(address: address);

/// Initialize an XMTP client with the given private key and database encryption key.
///
/// This connects to the XMTP production network, creates (or opens) an encrypted
/// local database, and registers the identity if needed.
///
/// Returns the Ethereum address of the initialized client.
Future<String> initializeClient(
        {required List<int> privateKey, required List<int> dbEncryptionKey, String environment = 'production'}) =>
    RustLib.instance.api.crateApiClientInitializeClient(
        privateKey: privateKey, dbEncryptionKey: dbEncryptionKey, environment: environment);

/// Get the current client's Ethereum address.
/// Returns an error if no client has been initialized.
Future<String> getClientAddress() =>
    RustLib.instance.api.crateApiClientGetClientAddress();

/// Get the current client's XMTP inbox ID.
/// Returns an error if no client has been initialized.
Future<String> getClientInboxId() =>
    RustLib.instance.api.crateApiClientGetClientInboxId();
