// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `consent_state_to_string`

/// Get the consent state for a conversation by topic.
/// Returns "allowed", "denied", or "unknown".
Future<String> getConversationConsentState({required String topic}) =>
    RustLib.instance.api
        .crateApiConsentGetConversationConsentState(topic: topic);

/// Set the consent state for a conversation by topic.
/// State must be "allowed", "denied", or "unknown".
Future<bool> setConversationConsentState(
        {required String topic, required String state}) =>
    RustLib.instance.api
        .crateApiConsentSetConversationConsentState(topic: topic, state: state);

/// Get the consent state for an inbox ID.
/// Returns "allowed", "denied", or "unknown".
Future<String> getInboxConsentState({required String inboxId}) =>
    RustLib.instance.api.crateApiConsentGetInboxConsentState(inboxId: inboxId);

/// Set the consent state for an inbox ID.
/// State must be "allowed", "denied", or "unknown".
Future<bool> setInboxConsentState(
        {required String inboxId, required String state}) =>
    RustLib.instance.api
        .crateApiConsentSetInboxConsentState(inboxId: inboxId, state: state);

/// Sync consent preferences across devices.
/// This syncs welcomes and history sync groups to propagate consent state.
Future<bool> syncConsentPreferences() =>
    RustLib.instance.api.crateApiConsentSyncConsentPreferences();
