// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'messaging.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// List all DM conversations, optionally filtered by consent state.
Future<List<ConversationInfo>> listDms({String? consentState}) =>
    RustLib.instance.api
        .crateApiConversationsListDms(consentState: consentState);

/// List all group conversations, optionally filtered by consent state.
Future<List<ConversationInfo>> listGroups({String? consentState}) =>
    RustLib.instance.api
        .crateApiConversationsListGroups(consentState: consentState);

/// List all conversations (DMs + groups), optionally filtered by consent state.
Future<List<ConversationInfo>> listConversations({String? consentState}) =>
    RustLib.instance.api
        .crateApiConversationsListConversations(consentState: consentState);

/// Find or create a DM with the given inbox ID. Returns the conversation info.
Future<ConversationInfo> findOrCreateDmWithInboxId({required String inboxId}) =>
    RustLib.instance.api
        .crateApiConversationsFindOrCreateDmWithInboxId(inboxId: inboxId);

/// Check if an address can receive XMTP messages.
Future<bool> canMessage({required String address}) =>
    RustLib.instance.api.crateApiConversationsCanMessage(address: address);

/// Look up the inbox ID for an Ethereum address from the XMTP network.
/// Returns empty string if the address has no inbox on the network.
Future<String> inboxIdFromAddress({required String address}) =>
    RustLib.instance.api
        .crateApiConversationsInboxIdFromAddress(address: address);

/// Get the conversation topic (hex-encoded group_id) for a DM with a given address.
/// This finds or creates the DM, so it may call the network.
Future<String> conversationTopicFromAddress({required String address}) =>
    RustLib.instance.api
        .crateApiConversationsConversationTopicFromAddress(address: address);

/// Sync all conversations (welcomes + groups).
/// Returns the number of groups synced.
Future<PlatformInt64> syncAll({List<String>? consentStates}) =>
    RustLib.instance.api
        .crateApiConversationsSyncAll(consentStates: consentStates);

/// Sync a single conversation by topic.
Future<void> syncConversation({required String topic}) =>
    RustLib.instance.api.crateApiConversationsSyncConversation(topic: topic);

/// Accept a conversation (set consent state to Allowed).
Future<bool> acceptConversation({required String topic}) =>
    RustLib.instance.api.crateApiConversationsAcceptConversation(topic: topic);

/// Deny a conversation (set consent state to Denied).
Future<bool> denyConversation({required String topic}) =>
    RustLib.instance.api.crateApiConversationsDenyConversation(topic: topic);

/// A conversation (DM or group), exposed to Dart.
class ConversationInfo {
  final String id;
  final String topic;
  final PlatformInt64 createdAtMs;
  final String conversationType;
  final String? peerInboxId;
  final String? name;
  final String? imageUrlSquare;
  final String? description;
  final List<MemberInfo> members;

  const ConversationInfo({
    required this.id,
    required this.topic,
    required this.createdAtMs,
    required this.conversationType,
    this.peerInboxId,
    this.name,
    this.imageUrlSquare,
    this.description,
    required this.members,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      topic.hashCode ^
      createdAtMs.hashCode ^
      conversationType.hashCode ^
      peerInboxId.hashCode ^
      name.hashCode ^
      imageUrlSquare.hashCode ^
      description.hashCode ^
      members.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConversationInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          topic == other.topic &&
          createdAtMs == other.createdAtMs &&
          conversationType == other.conversationType &&
          peerInboxId == other.peerInboxId &&
          name == other.name &&
          imageUrlSquare == other.imageUrlSquare &&
          description == other.description &&
          members == other.members;
}
