// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'conversations.dart';
import 'messaging.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `identifier_to_parts`

/// Create a new group with the given inbox IDs and optional metadata.
/// Returns the conversation info for the new group.
Future<ConversationInfo> newGroup(
        {required List<String> inboxIds,
        String? name,
        String? imageUrlSquare,
        String? description}) =>
    RustLib.instance.api.crateApiGroupsNewGroup(
        inboxIds: inboxIds,
        name: name,
        imageUrlSquare: imageUrlSquare,
        description: description);

/// List all members of a group.
Future<List<MemberInfo>> listGroupMembers({required String topic}) =>
    RustLib.instance.api.crateApiGroupsListGroupMembers(topic: topic);

/// List admin inbox IDs for a group.
Future<List<String>> listGroupAdmins({required String topic}) =>
    RustLib.instance.api.crateApiGroupsListGroupAdmins(topic: topic);

/// List super admin inbox IDs for a group.
Future<List<String>> listGroupSuperAdmins({required String topic}) =>
    RustLib.instance.api.crateApiGroupsListGroupSuperAdmins(topic: topic);

/// Add members to a group by their inbox IDs.
Future<bool> addGroupMembers(
        {required String topic, required List<String> inboxIds}) =>
    RustLib.instance.api
        .crateApiGroupsAddGroupMembers(topic: topic, inboxIds: inboxIds);

/// Remove members from a group by their inbox IDs.
Future<bool> removeGroupMembers(
        {required String topic, required List<String> inboxIds}) =>
    RustLib.instance.api
        .crateApiGroupsRemoveGroupMembers(topic: topic, inboxIds: inboxIds);

/// Add an inbox ID to the admin list.
Future<bool> addGroupAdmin({required String topic, required String inboxId}) =>
    RustLib.instance.api
        .crateApiGroupsAddGroupAdmin(topic: topic, inboxId: inboxId);

/// Remove an inbox ID from the admin list.
Future<bool> removeGroupAdmin(
        {required String topic, required String inboxId}) =>
    RustLib.instance.api
        .crateApiGroupsRemoveGroupAdmin(topic: topic, inboxId: inboxId);

/// Add an inbox ID to the super admin list.
Future<bool> addGroupSuperAdmin(
        {required String topic, required String inboxId}) =>
    RustLib.instance.api
        .crateApiGroupsAddGroupSuperAdmin(topic: topic, inboxId: inboxId);

/// Remove an inbox ID from the super admin list.
Future<bool> removeGroupSuperAdmin(
        {required String topic, required String inboxId}) =>
    RustLib.instance.api
        .crateApiGroupsRemoveGroupSuperAdmin(topic: topic, inboxId: inboxId);

/// Update group metadata (name, description, image URL).
/// Only non-None fields are updated.
Future<bool> updateGroup(
        {required String topic,
        String? name,
        String? description,
        String? imageUrl}) =>
    RustLib.instance.api.crateApiGroupsUpdateGroup(
        topic: topic, name: name, description: description, imageUrl: imageUrl);

/// Get the admin/super-admin role for a member in a group.
Future<MemberRoleInfo> getGroupMemberRole(
        {required String topic, required String inboxId}) =>
    RustLib.instance.api
        .crateApiGroupsGetGroupMemberRole(topic: topic, inboxId: inboxId);

/// Get the association state for each inbox ID.
/// Returns identity, installation, and recovery information.
Future<List<InboxStateInfo>> inboxStatesForInboxIds(
        {required List<String> inboxIds, required bool refreshFromNetwork}) =>
    RustLib.instance.api.crateApiGroupsInboxStatesForInboxIds(
        inboxIds: inboxIds, refreshFromNetwork: refreshFromNetwork);

/// An identity (Ethereum address or passkey) associated with an inbox.
class IdentityInfo {
  final String identifier;
  final String kind;

  const IdentityInfo({
    required this.identifier,
    required this.kind,
  });

  @override
  int get hashCode => identifier.hashCode ^ kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IdentityInfo &&
          runtimeType == other.runtimeType &&
          identifier == other.identifier &&
          kind == other.kind;
}

/// Full inbox state for a given inbox ID.
class InboxStateInfo {
  final String inboxId;
  final List<IdentityInfo> identities;
  final List<InstallationInfo> installations;
  final IdentityInfo recoveryIdentity;

  const InboxStateInfo({
    required this.inboxId,
    required this.identities,
    required this.installations,
    required this.recoveryIdentity,
  });

  @override
  int get hashCode =>
      inboxId.hashCode ^
      identities.hashCode ^
      installations.hashCode ^
      recoveryIdentity.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InboxStateInfo &&
          runtimeType == other.runtimeType &&
          inboxId == other.inboxId &&
          identities == other.identities &&
          installations == other.installations &&
          recoveryIdentity == other.recoveryIdentity;
}

/// An MLS installation associated with an inbox.
class InstallationInfo {
  final String id;
  final PlatformInt64? createdAt;

  const InstallationInfo({
    required this.id,
    this.createdAt,
  });

  @override
  int get hashCode => id.hashCode ^ createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InstallationInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          createdAt == other.createdAt;
}

/// Role information for a group member.
class MemberRoleInfo {
  final bool isAdmin;
  final bool isSuperAdmin;

  const MemberRoleInfo({
    required this.isAdmin,
    required this.isSuperAdmin,
  });

  @override
  int get hashCode => isAdmin.hashCode ^ isSuperAdmin.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MemberRoleInfo &&
          runtimeType == other.runtimeType &&
          isAdmin == other.isAdmin &&
          isSuperAdmin == other.isSuperAdmin;
}
