// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'groups.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `identifier_to_parts`

/// Get the current client's installation ID (hex-encoded public key).
Future<String> getInstallationId() =>
    RustLib.instance.api.crateApiInboxGetInstallationId();

/// Get the current client's inbox state.
/// Returns identity, installation, and recovery information.
Future<InboxStateInfo> getInboxState({required bool refreshFromNetwork}) =>
    RustLib.instance.api
        .crateApiInboxGetInboxState(refreshFromNetwork: refreshFromNetwork);

/// Send a sync request to other installations.
/// Triggers history sync from existing devices.
Future<bool> sendSyncRequest() =>
    RustLib.instance.api.crateApiInboxSendSyncRequest();
