// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

/// Send a DM to a peer by Ethereum address.
/// Finds or creates the DM conversation, then sends the message.
/// Returns the hex-encoded message ID.
Future<String> sendMessage(
        {required String address, required List<int> contentBytes}) =>
    RustLib.instance.api.crateApiMessagingSendMessage(
        address: address, contentBytes: contentBytes);

/// Send a DM to a peer by inbox ID.
/// Returns the hex-encoded message ID.
Future<String> sendMessageByInboxId(
        {required String inboxId, required List<int> contentBytes}) =>
    RustLib.instance.api.crateApiMessagingSendMessageByInboxId(
        inboxId: inboxId, contentBytes: contentBytes);

/// Send a message to a group/conversation by topic (hex-encoded group_id).
/// Returns the hex-encoded message ID.
Future<String> sendGroupMessage(
        {required String topic, required List<int> contentBytes}) =>
    RustLib.instance.api.crateApiMessagingSendGroupMessage(
        topic: topic, contentBytes: contentBytes);

/// Get messages from a DM conversation after a given date (milliseconds since epoch).
/// Syncs the conversation first, then queries locally.
Future<List<MessageInfo>> getMessagesAfterDate(
        {required String peerAddress, required PlatformInt64 fromDateMs}) =>
    RustLib.instance.api.crateApiMessagingGetMessagesAfterDate(
        peerAddress: peerAddress, fromDateMs: fromDateMs);

/// Get messages from a conversation by topic after a given date (milliseconds since epoch).
Future<List<MessageInfo>> getMessagesAfterDateByTopic(
        {required String topic, required PlatformInt64 fromDateMs}) =>
    RustLib.instance.api.crateApiMessagingGetMessagesAfterDateByTopic(
        topic: topic, fromDateMs: fromDateMs);

/// Subscribe to all incoming messages across all conversations.
/// Messages are pushed to the StreamSink as they arrive.
/// The stream runs until the Dart side cancels the subscription.
Stream<MessageInfo> subscribeToAllMessages() =>
    RustLib.instance.api.crateApiMessagingSubscribeToAllMessages();

/// Download and decrypt a remote attachment.
/// Fetches the encrypted payload from the URL, verifies the content digest,
/// decrypts with HKDF-SHA256 + AES-256-GCM, and returns the attachment.
Future<AttachmentInfo> loadRemoteAttachment(
        {required String url,
        required String contentDigest,
        required List<int> secret,
        required List<int> salt,
        required List<int> nonce,
        required String scheme,
        PlatformInt64? contentLength,
        String? filename}) =>
    RustLib.instance.api.crateApiMessagingLoadRemoteAttachment(
        url: url,
        contentDigest: contentDigest,
        secret: secret,
        salt: salt,
        nonce: nonce,
        scheme: scheme,
        contentLength: contentLength,
        filename: filename);

/// A decrypted remote attachment, exposed to Dart.
class AttachmentInfo {
  final String filename;
  final String mimeType;
  final Uint8List data;

  const AttachmentInfo({
    required this.filename,
    required this.mimeType,
    required this.data,
  });

  @override
  int get hashCode => filename.hashCode ^ mimeType.hashCode ^ data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AttachmentInfo &&
          runtimeType == other.runtimeType &&
          filename == other.filename &&
          mimeType == other.mimeType &&
          data == other.data;
}

/// A member of a conversation, exposed to Dart.
class MemberInfo {
  final String inboxId;
  final String address;

  const MemberInfo({
    required this.inboxId,
    required this.address,
  });

  @override
  int get hashCode => inboxId.hashCode ^ address.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MemberInfo &&
          runtimeType == other.runtimeType &&
          inboxId == other.inboxId &&
          address == other.address;
}

/// A message, exposed to Dart.
class MessageInfo {
  final String id;
  final PlatformInt64 sentAtMs;
  final String senderInboxId;
  final String conversationTopic;
  final Uint8List encodedContentBytes;
  final List<MemberInfo> members;

  const MessageInfo({
    required this.id,
    required this.sentAtMs,
    required this.senderInboxId,
    required this.conversationTopic,
    required this.encodedContentBytes,
    required this.members,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      sentAtMs.hashCode ^
      senderInboxId.hashCode ^
      conversationTopic.hashCode ^
      encodedContentBytes.hashCode ^
      members.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          sentAtMs == other.sentAtMs &&
          senderInboxId == other.senderInboxId &&
          conversationTopic == other.conversationTopic &&
          encodedContentBytes == other.encodedContentBytes &&
          members == other.members;
}
