// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'conversations.dart';
import 'messaging.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `format_group_topic`, `parse_group_topic`

/// Get all HMAC keys for every conversation the client knows about, including
/// stitched duplicate DMs. Flattened to `Vec<HmacKeyEntry>` for easier Dart
/// consumption (libxmtp's native shape is `HashMap<group_id, Vec<HmacKey>>`).
///
/// The notification server's `subscribeWithMetadata` endpoint takes these
/// `(topic, hmac_key, epoch)` triples to filter messages on its XMTP listener
/// side while preserving end-to-end encryption.
Future<List<HmacKeyEntry>> getAllHmacKeys() =>
    RustLib.instance.api.crateApiPushGetAllHmacKeys();

/// Decrypt an FCM/APNs push payload for an existing conversation.
///
/// Returns `Vec<MessageInfo>` because libxmtp may surface multiple decoded
/// messages from a single envelope (rare but possible). Caller should handle
/// the multi-message case; empty Vec is valid if the payload contained no
/// application content (commit-only, etc.).
Future<List<MessageInfo>> processPushMessage(
        {required String topic, required List<int> encryptedBytes}) =>
    RustLib.instance.api.crateApiPushProcessPushMessage(
        topic: topic, encryptedBytes: encryptedBytes);

/// Decrypt an FCM/APNs push payload that arrived on the welcome topic
/// (`/xmtp/mls/1/w-${installation_id}/proto`).
///
/// Returns `Vec<ConversationInfo>` because a single welcome envelope may
/// produce multiple conversations when DM stitching applies.
Future<List<ConversationInfo>> processWelcome(
        {required List<int> encryptedBytes}) =>
    RustLib.instance.api
        .crateApiPushProcessWelcome(encryptedBytes: encryptedBytes);

/// One HMAC key for one conversation topic, valid for a 30-day epoch window.
///
/// libxmtp rotates HMAC keys every 30 days. `get_all_hmac_keys` returns three
/// keys per conversation (prior epoch, current, next) so the notification
/// server can keep matching push deliveries across epoch boundaries without
/// the client re-subscribing.
class HmacKeyEntry {
  /// Hex-encoded conversation topic (matches `MessageInfo.conversation_topic`).
  final String topic;

  /// Raw HMAC key bytes for this epoch.
  final Uint8List hmacKey;

  /// Which 30-day epoch this key belongs to. The current epoch is computed
  /// as `floor(unix_seconds / (30 * 86400))`.
  final PlatformInt64 thirtyDayPeriodsSinceEpoch;

  const HmacKeyEntry({
    required this.topic,
    required this.hmacKey,
    required this.thirtyDayPeriodsSinceEpoch,
  });

  @override
  int get hashCode =>
      topic.hashCode ^ hmacKey.hashCode ^ thirtyDayPeriodsSinceEpoch.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HmacKeyEntry &&
          runtimeType == other.runtimeType &&
          topic == other.topic &&
          hmacKey == other.hmacKey &&
          thirtyDayPeriodsSinceEpoch == other.thirtyDayPeriodsSinceEpoch;
}
