// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'groups.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `eip191_sign`, `identifier_to_parts`

/// Revoke specific installations by their hex-encoded IDs.
/// Requires the recovery wallet's private key to sign the revocation.
Future<bool> revokeInstallations(
        {required List<int> signerPrivateKey,
        required List<String> installationIds}) =>
    RustLib.instance.api.crateApiSigningRevokeInstallations(
        signerPrivateKey: signerPrivateKey, installationIds: installationIds);

/// Revoke all installations except the current one.
/// Useful for "log out all other devices" functionality.
Future<bool> revokeAllOtherInstallations(
        {required List<int> signerPrivateKey}) =>
    RustLib.instance.api.crateApiSigningRevokeAllOtherInstallations(
        signerPrivateKey: signerPrivateKey);

/// Remove an identity (wallet address) from the current inbox.
/// Requires the recovery wallet's private key to sign.
/// The identity being removed cannot be the recovery identity.
Future<bool> removeAccount(
        {required List<int> recoveryPrivateKey,
        required String identifierToRemove}) =>
    RustLib.instance.api.crateApiSigningRemoveAccount(
        recoveryPrivateKey: recoveryPrivateKey,
        identifierToRemove: identifierToRemove);

/// Add a new identity (wallet address) to the current inbox.
/// `associate_identity` internally signs with the installation key as the
/// existing member, so we only need to provide the new member's signature.
Future<bool> addAccount({required List<int> newAccountPrivateKey}) =>
    RustLib.instance.api
        .crateApiSigningAddAccount(newAccountPrivateKey: newAccountPrivateKey);

/// Revoke installations without an active client.
/// Creates a temporary API connection to perform the revocation.
Future<bool> staticRevokeInstallations(
        {required List<int> signerPrivateKey,
        required String inboxId,
        required List<String> installationIds}) =>
    RustLib.instance.api.crateApiSigningStaticRevokeInstallations(
        signerPrivateKey: signerPrivateKey,
        inboxId: inboxId,
        installationIds: installationIds);

/// Get inbox states without an active client.
/// Creates a temporary API connection and ephemeral DB.
Future<List<InboxStateInfo>> staticInboxStatesForInboxIds(
        {required List<String> inboxIds}) =>
    RustLib.instance.api
        .crateApiSigningStaticInboxStatesForInboxIds(inboxIds: inboxIds);
